# Generated by Django 3.2.3 on 2022-10-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConApp', '0002_mynotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamedNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MyNotes',
            new_name='MamadouNotes',
        ),
    ]
